#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

#include "raycommon.glsl"

layout(binding = 15, set = 1, scalar) buffer Aabbs { aabb aabbs[]; };


void main()
{
    aabb bb = aabbs[gl_PrimitiveID];

    if (min(bb.min, gl_WorldRayOriginEXT) == bb.min && max(bb.max, gl_WorldRayOriginEXT) == bb.max) {
        reportIntersectionEXT(0, 0);
    }
}